### ISSUE TITLE
执行start_sshd.sh报错

### ISSUE THREAD

**Issue by adsfklj-djasklf** [jm33-m0/SSH-Harvester#2]
```
autoreconf: error: 'configure.ac' is required
./start_sshd.sh: line 13: /root/SSH-Harvester/sshd: No such file or directory
```
操作系统 Ubuntu 2204
内核版本 Linux ubuntu 5.15.0-105-generic
ssh版本  OpenSSH_8.9p1 Ubuntu-3ubuntu0.7

**Comment by jm33-m0** [comment]
Read the script, it requires you to either build the sshd binary yourself or have the source code ready in current directory.
